# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'hovearm-conn'
    subscriptionId: '01649a75-9ad9-4710-9298-e2eac4e1a893'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'brian'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/WisdomHove/hovearm/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName hovearm'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
